#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NATIVE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PACKAGE_DIR="$(cd "${NATIVE_DIR}/.." && pwd)"
VENDOR_DIR="${NATIVE_DIR}/vendor"
LIBJPEG_DIR="${VENDOR_DIR}/libjpeg-turbo-3.1.4.1"
BUILD_DIR="${NATIVE_DIR}/build"
OUTPUT_DIR="${PACKAGE_DIR}/dist/native"
OUTPUT_JS="${OUTPUT_DIR}/luma_jpeg.js"

source "${NATIVE_DIR}/emcc-flags.sh"

if ! command -v emcc >/dev/null 2>&1; then
  echo "emcc is required. Activate the Emscripten SDK before running build:native." >&2
  exit 1
fi

if [ ! -d "${LIBJPEG_DIR}" ]; then
  echo "Missing libjpeg-turbo source directory: ${LIBJPEG_DIR}" >&2
  echo "Run native/scripts/fetch-sources.mjs before building." >&2
  exit 1
fi

rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}" "${OUTPUT_DIR}"

cat > "${BUILD_DIR}/jconfig.h" <<'EOF'
/* Generated by LumaForge's Emscripten skeleton build. */
#define JPEG_LIB_VERSION  62
#define LIBJPEG_TURBO_VERSION  "3.1.4.1"
#define LIBJPEG_TURBO_VERSION_NUMBER  3001004
#define MEM_SRCDST_SUPPORTED  1

#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE  8
#endif
EOF

cat > "${BUILD_DIR}/jconfigint.h" <<'EOF'
/* Generated by LumaForge's Emscripten skeleton build. */
#define BUILD  "luma-wasm"
#define HIDDEN  __attribute__((visibility("hidden")))
#undef inline
#define INLINE  inline __attribute__((always_inline))
#define THREAD_LOCAL  __thread
#define PACKAGE_NAME  "libjpeg-turbo"
#define VERSION  "3.1.4.1"
#define SIZEOF_SIZE_T  4
#define HAVE_BUILTIN_CTZL

#if defined(__has_attribute)
#if __has_attribute(fallthrough)
#define FALLTHROUGH  __attribute__((fallthrough));
#else
#define FALLTHROUGH
#endif
#else
#define FALLTHROUGH
#endif

#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE  8
#endif

#undef C_ARITH_CODING_SUPPORTED
#undef D_ARITH_CODING_SUPPORTED
#undef WITH_SIMD
EOF

sed 's/@COPYRIGHT_YEAR@/1991-2026/g' "${LIBJPEG_DIR}/src/jversion.h.in" > "${BUILD_DIR}/jversion.h"

emcc \
  --bind \
  -I"${BUILD_DIR}" \
  -I"${LIBJPEG_DIR}" \
  -I"${LIBJPEG_DIR}/src" \
  ${LUMA_JPEG_CFLAGS} \
  ${LUMA_JPEG_LDFLAGS} \
  "${NATIVE_DIR}/libjpeg_turbo_encoder.cpp" \
  "${LIBJPEG_DIR}/src/jcapimin.c" \
  "${LIBJPEG_DIR}/src/jcapistd.c" \
  "${LIBJPEG_DIR}/src/jccoefct.c" \
  "${LIBJPEG_DIR}/src/jccolor.c" \
  "${LIBJPEG_DIR}/src/jcdctmgr.c" \
  "${LIBJPEG_DIR}/src/jcdiffct.c" \
  "${LIBJPEG_DIR}/src/jchuff.c" \
  "${LIBJPEG_DIR}/src/jcicc.c" \
  "${LIBJPEG_DIR}/src/jcinit.c" \
  "${LIBJPEG_DIR}/src/jclhuff.c" \
  "${LIBJPEG_DIR}/src/jclossls.c" \
  "${LIBJPEG_DIR}/src/jcmainct.c" \
  "${LIBJPEG_DIR}/src/jcmarker.c" \
  "${LIBJPEG_DIR}/src/jcmaster.c" \
  "${LIBJPEG_DIR}/src/jcomapi.c" \
  "${LIBJPEG_DIR}/src/jcparam.c" \
  "${LIBJPEG_DIR}/src/jcphuff.c" \
  "${LIBJPEG_DIR}/src/jcprepct.c" \
  "${LIBJPEG_DIR}/src/jcsample.c" \
  "${LIBJPEG_DIR}/src/jctrans.c" \
  "${LIBJPEG_DIR}/src/jdapimin.c" \
  "${LIBJPEG_DIR}/src/jdapistd.c" \
  "${LIBJPEG_DIR}/src/jdatadst.c" \
  "${LIBJPEG_DIR}/src/jdatasrc.c" \
  "${LIBJPEG_DIR}/src/jdcoefct.c" \
  "${LIBJPEG_DIR}/src/jdcolor.c" \
  "${LIBJPEG_DIR}/src/jddctmgr.c" \
  "${LIBJPEG_DIR}/src/jdhuff.c" \
  "${LIBJPEG_DIR}/src/jdicc.c" \
  "${LIBJPEG_DIR}/src/jdinput.c" \
  "${LIBJPEG_DIR}/src/jdmainct.c" \
  "${LIBJPEG_DIR}/src/jdmarker.c" \
  "${LIBJPEG_DIR}/src/jdmaster.c" \
  "${LIBJPEG_DIR}/src/jdmerge.c" \
  "${LIBJPEG_DIR}/src/jdphuff.c" \
  "${LIBJPEG_DIR}/src/jdpostct.c" \
  "${LIBJPEG_DIR}/src/jdsample.c" \
  "${LIBJPEG_DIR}/src/jdtrans.c" \
  "${LIBJPEG_DIR}/src/jerror.c" \
  "${LIBJPEG_DIR}/src/jfdctflt.c" \
  "${LIBJPEG_DIR}/src/jfdctfst.c" \
  "${LIBJPEG_DIR}/src/jfdctint.c" \
  "${LIBJPEG_DIR}/src/jidctflt.c" \
  "${LIBJPEG_DIR}/src/jidctfst.c" \
  "${LIBJPEG_DIR}/src/jidctint.c" \
  "${LIBJPEG_DIR}/src/jquant1.c" \
  "${LIBJPEG_DIR}/src/jquant2.c" \
  "${LIBJPEG_DIR}/src/jutils.c" \
  "${LIBJPEG_DIR}/src/jpeg_nbits.c" \
  "${LIBJPEG_DIR}/src/jmemmgr.c" \
  "${LIBJPEG_DIR}/src/jmemnobs.c" \
  "${LIBJPEG_DIR}/src/wrapper/jccoefct-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jccolor-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jccolor-16.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcdctmgr-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcdiffct-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcdiffct-16.c" \
  "${LIBJPEG_DIR}/src/wrapper/jfdctfst-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jfdctint-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jclossls-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jclossls-16.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcmainct-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcmainct-16.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcprepct-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcprepct-16.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcsample-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jcsample-16.c" \
  "${LIBJPEG_DIR}/src/wrapper/jutils-12.c" \
  "${LIBJPEG_DIR}/src/wrapper/jutils-16.c" \
  -o "${OUTPUT_JS}"

node "${SCRIPT_DIR}/verify-native-artifacts.mjs" --write-provenance

echo "Built Luma JPEG native runtime into ${OUTPUT_DIR}"
