#!/usr/bin/env bash

set -euo pipefail

LUMA_RAW_MEMORY_PROFILE="${LUMA_RAW_MEMORY_PROFILE:-desktop}"

case "${LUMA_RAW_MEMORY_PROFILE}" in
  desktop)
    export LUMA_RAW_CFLAGS="-O3 -flto -ffast-math -msimd128 -DNDEBUG -DUSE_LCMS2"
    export LUMA_RAW_LDFLAGS="-O3 -flto -pthread -s USE_PTHREADS=1 -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web,worker -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=256MB -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_ZLIB=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_RUNTIME_METHODS=HEAPU8"
    ;;
  low-memory)
    export LUMA_RAW_CFLAGS="-O3 -flto -ffast-math -msimd128 -DNDEBUG -DUSE_LCMS2"
    export LUMA_RAW_LDFLAGS="-O3 -flto -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web,worker -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_HEAP=64MB -s MAXIMUM_MEMORY=1024MB -s MEMORY_GROWTH_LINEAR_STEP=16MB -s ABORTING_MALLOC=0 -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_ZLIB=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_RUNTIME_METHODS=HEAPU8"
    ;;
  *)
    echo "Unknown LUMA_RAW_MEMORY_PROFILE: ${LUMA_RAW_MEMORY_PROFILE}" >&2
    exit 1
    ;;
esac
