#!/usr/bin/env bash

set -euo pipefail

export LUMA_RAW_CFLAGS="-O3 -flto -ffast-math -msimd128 -DNDEBUG -DUSE_LCMS2"
export LUMA_RAW_LDFLAGS="-O3 -flto -pthread -s USE_PTHREADS=1 -s MODULARIZE=1 -s EXPORT_ES6=1 -s ENVIRONMENT=web,worker -s ALLOW_MEMORY_GROWTH=1 -s INITIAL_MEMORY=256MB -s USE_LIBPNG=1 -s USE_LIBJPEG=1 -s USE_ZLIB=1 -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_RUNTIME_METHODS=HEAPU8"
